# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title


# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : 寂寞的宾狗
tagline: A dog lives in winter
description:      '宾狗的后院'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'bindog'
linkedin:       'https://ae.linkedin.com/in/bindog/'
twitter:        'https://twitter.com/bindog'
facebook:       'https://www.facebook.com/bindog'
gplus:          'https://plus.google.com/bindog'


# Disqus
disqushandler: 'bindog'

# Blog Configurations
paginate: 3 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.8
